# Generated by Django 2.1.3 on 2018-12-06 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_address', '0002_collectionaddress_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaddress',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
