# Generated by Django 2.1.3 on 2018-12-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
