# Generated by Django 2.1.3 on 2018-12-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_address', '0002_deliveryaddress_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='line2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
