# Generated by Django 2.1.3 on 2018-12-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_address', '0003_auto_20181206_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('collection_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipientsName', models.CharField(max_length=35)),
                ('recipientsSurname', models.CharField(max_length=35)),
                ('collection_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_address', to='collection_address.CollectionAddress')),
                ('delivery_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='delivery_address.DeliveryAddress')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
