# Generated by Django 2.1.1 on 2018-11-10 14:35

from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=35, validators=[user.validators.validate_Symbol, user.validators.validate_legnth, user.validators.validate_number, user.validators.validate_Uppercase])),
                ('birthDate', models.DateField(max_length=8, validators=[user.validators.validate_birthDate])),
                ('firstName', models.CharField(max_length=35)),
                ('secondName', models.CharField(max_length=35)),
                ('firstSurname', models.CharField(max_length=35)),
                ('secondSurname', models.CharField(max_length=35)),
                ('collection_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_address.CollectionAddress')),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
    ]
